# Generated by Django 4.0.3 on 2022-05-21 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='follower',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='following',
            new_name='target_following',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='following',
        ),
        migrations.AddField(
            model_name='customuser',
            name='my_followers',
            field=models.ManyToManyField(null=True, related_name='user_followers', through='users.Following', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='following',
            name='user_follower',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='following',
            constraint=models.UniqueConstraint(fields=('user_follower', 'target_following'), name='unique_followers'),
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
