# Generated by Django 4.0.4 on 2022-05-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='mario.jpg', null=True, upload_to='avatars'),
        ),
    ]
