# Generated by Django 4.0.3 on 2022-05-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='following',
        ),
        migrations.AddField(
            model_name='customuser',
            name='my_followers',
            field=models.ManyToManyField(blank=True, related_name='user_followers', through='users.Followers', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='my_followings',
            field=models.ManyToManyField(blank=True, related_name='user_followings', through='users.Following', to='users.customuser'),
        ),
    ]
