# Generated by Django 4.0.3 on 2022-05-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_followers_follower_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='following',
            name='unique_followers',
        ),
        migrations.AddConstraint(
            model_name='following',
            constraint=models.UniqueConstraint(fields=('_id', 'user_follower', 'target_following'), name='unique_id'),
        ),
    ]
