# Generated by Django 4.0.3 on 2022-05-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_following_unique_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='following',
            name='unique_id',
        ),
        migrations.AddConstraint(
            model_name='following',
            constraint=models.UniqueConstraint(fields=('user_follower', 'target_following'), name='unique_id'),
        ),
    ]
