# Generated by Django 4.0.3 on 2022-05-21 19:36

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_following_unique_id_following_unique_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='following',
            name='unique_id',
        ),
        migrations.AddConstraint(
            model_name='following',
            constraint=models.UniqueConstraint(fields=('user_follower', 'target_following'), name='unique_follow'),
        ),
        migrations.AddConstraint(
            model_name='following',
            constraint=models.CheckConstraint(check=models.Q(('user_follower', django.db.models.expressions.F('target_following')), _negated=True), name='check_unique'),
        ),
    ]
