# Generated by Django 4.0.3 on 2022-05-21 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_remove_following_unique_id_following_unique_follow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='my_followers',
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_followers', models.ManyToManyField(related_name='user_followers', through='users.Following', to='users.followers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
