# Generated by Django 4.0.3 on 2022-05-21 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_followers_following_remove_customuser_friends_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='followers',
            new_name='my_followers',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='following',
            new_name='my_followings',
        ),
    ]
