# Generated by Django 4.0.4 on 2022-05-25 03:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threads', '0004_threadcomments_dislikes_threadcomments_likes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThreadComments',
            new_name='ThreadComment',
        ),
    ]
