# Generated by Django 4.0.4 on 2022-05-25 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_rename_threadcomments_threadcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threadcomment',
            old_name='thread',
            new_name='root',
        ),
    ]
