# Generated by Django 4.0.4 on 2022-05-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0006_rename_thread_threadcomment_root'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadcomment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='threadcomment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='threadcomment',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='threadcomment',
            name='root',
        ),
    ]
