# Generated by Django 4.0.4 on 2022-05-25 18:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0007_remove_threadcomment_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadcomment',
            name='parent_thread',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='thread_comments', to='threads.thread'),
            preserve_default=False,
        ),
    ]
