# Generated by Django 4.0.4 on 2022-05-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0008_threadcomment_parent_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadcomment',
            name='parent_thread',
        ),
    ]
