# Generated by Django 4.0.4 on 2022-05-25 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0009_remove_threadcomment_parent_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadcomment',
            name='parent_thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_comments', to='threads.thread'),
        ),
    ]
