# Generated by Django 4.0.4 on 2022-05-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0010_threadcomment_parent_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadcomment',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='threadcomment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='threadcomment',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
