# Generated by Django 4.0.4 on 2022-05-25 19:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threads', '0012_thread_comment_delete_threadcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thread_comment',
            new_name='ThreadComment',
        ),
    ]
