# Generated by Django 4.0.4 on 2022-05-26 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0017_rename_thread_comment_threadcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadcomment',
            name='published_date',
        ),
    ]
