# Generated by Django 4.0.4 on 2022-05-26 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0018_remove_threadcomment_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadcomment',
            name='parent_thread',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_comments', to='threads.thread'),
        ),
    ]
