# Generated by Django 4.0.4 on 2022-05-26 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0025_threadcomment_delete_thread_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadcomment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
